services:
  redis:
    image: redis:latest
    container_name: redis_instance
    ports:
      - "6379:6379"
    command:
      ["redis-server", "--save", "", "--appendonly", "no"]
    restart: 
      always
    networks:
      - backend

  rate_limiter:
    container_name: rate_limiter
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    restart:
      always
    networks:
      - backend
    depends_on:
      - redis

networks:
  backend:
    driver: bridge