services:
  redis:
    image: redis:latest
    container_name: redis_instance
    ports:
      - "6379:6379"
    volumes:
      - /data:/data
    restart: always

  rate_limiter:
    image: golang:1.23.0
    container_name: rate_limiter
    build:
      context: .
      dockerfile: Dockerfile